/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom23.quanlytiennuoc.ui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nhom23.quanlytiennuoc.helpers.DataValidator;
import nhom23.quanlytiennuoc.helpers.SharedData;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {
    private QuanLyKhachHang quanLyKhachHang = null;
    private QuanLyTaiKhoan quanLyTaiKhoan = null;
    private QuanLyBienLai quanLyBienLai = null;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Phần mềm quản lý tiền nước");
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        popMenu = new javax.swing.JPopupMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        tbrLogout = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        tbrQLBL = new javax.swing.JButton();
        tbrQLKH = new javax.swing.JButton();
        tbrQLTK = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        tbrAboutUs = new javax.swing.JButton();
        tbpMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTenHienThi = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemBL = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemKH = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuItemTK = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemNd = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuItemAboutUs = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        popMenu.setMinimumSize(new java.awt.Dimension(20, 20));

        jMenu4.setText("Chức năng");

        jMenuItem3.setText("Quản lý biên lai");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);
        jMenu4.add(jSeparator10);

        jMenuItem1.setText("Quản lý khách hàng");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator11);

        jMenuItem9.setText("Quản lý tài khoản");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        popMenu.add(jMenu4);
        popMenu.add(jSeparator8);

        jMenu5.setText("Hệ thống");

        jMenuItem4.setText("Đăng xuất");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);
        jMenu5.add(jSeparator12);

        jMenuItem5.setText("Thoát");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        popMenu.add(jMenu5);
        popMenu.add(jSeparator9);

        jMenu6.setText("Trợ giúp");

        jMenuItem7.setText("Thông tin");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);
        jMenu6.add(jSeparator13);

        jMenuItem8.setText("Trợ giúp");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        popMenu.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setComponentPopupMenu(popMenu);

        tbrLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/logout-icon-32.png"))); // NOI18N
        tbrLogout.setText("Đăng xuất");
        tbrLogout.setFocusable(false);
        tbrLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLogout);
        jToolBar1.add(jSeparator6);

        tbrQLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_receipt_32px_1.png"))); // NOI18N
        tbrQLBL.setText("Quản lý biên lai");
        tbrQLBL.setFocusable(false);
        tbrQLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrQLBL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrQLBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrQLBLActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrQLBL);

        tbrQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_group_32px_1.png"))); // NOI18N
        tbrQLKH.setText("Quản lý khách hàng");
        tbrQLKH.setFocusable(false);
        tbrQLKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrQLKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrQLKHActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrQLKH);

        tbrQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_key_2_32px_1.png"))); // NOI18N
        tbrQLTK.setText("Quản lý tài khoản");
        tbrQLTK.setFocusable(false);
        tbrQLTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrQLTK.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrQLTKActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrQLTK);
        jToolBar1.add(jSeparator7);

        tbrAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_info_32px.png"))); // NOI18N
        tbrAboutUs.setText("Giới thiệu");
        tbrAboutUs.setFocusable(false);
        tbrAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAboutUs);

        tbpMain.setComponentPopupMenu(popMenu);
        tbpMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbpMainStateChanged(evt);
            }
        });
        tbpMain.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbpMainPropertyChange(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTenHienThi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenHienThi.setForeground(new java.awt.Color(255, 51, 0));
        lblTenHienThi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenHienThi.setText("Tên hiển thị");

        lblVaiTro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVaiTro.setText("Vai trò");
        lblVaiTro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_user_32px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTenHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblTenHienThi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaiTro))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lblStatus.setForeground(new java.awt.Color(0, 255, 51));
        lblStatus.setText("Trạng thái:");

        jLabel2.setText("Thời gian:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, lblStatus});

        jMenu1.setMnemonic('h');
        jMenu1.setText("Hệ thống");
        jMenu1.setToolTipText("");

        menuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/logout-icon-16.png"))); // NOI18N
        menuItemLogout.setMnemonic('o');
        menuItemLogout.setText("Đăng xuất");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemLogout);
        jMenu1.add(jSeparator1);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Button-Close-icon-16.png"))); // NOI18N
        menuItemExit.setMnemonic('t');
        menuItemExit.setText("Thoát");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('q');
        jMenu2.setText("Quản lý");

        menuItemBL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_receipt_16px_1.png"))); // NOI18N
        menuItemBL.setMnemonic('b');
        menuItemBL.setText("Quản lý biên lai");
        menuItemBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBLActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemBL);
        jMenu2.add(jSeparator2);

        menuItemKH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_conference_16px_1.png"))); // NOI18N
        menuItemKH.setMnemonic('k');
        menuItemKH.setText("Quản lý khách hàng");
        menuItemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKHActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemKH);
        jMenu2.add(jSeparator4);

        menuItemTK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_key_2_16px_1.png"))); // NOI18N
        menuItemTK.setMnemonic('k');
        menuItemTK.setText("Quản lý tài khoản");
        menuItemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTKActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemTK);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('t');
        jMenu3.setText("Trợ giúp");

        menuItemNd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItemNd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Actions-help-about-icon-16.png"))); // NOI18N
        menuItemNd.setMnemonic('n');
        menuItemNd.setText("Nội dung");
        menuItemNd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNdActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemNd);
        jMenu3.add(jSeparator5);

        menuItemAboutUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Help-icon-16.png"))); // NOI18N
        menuItemAboutUs.setMnemonic('g');
        menuItemAboutUs.setText("Giới thiệu");
        menuItemAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutUsActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemAboutUs);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(tbpMain)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKHActionPerformed
        if(quanLyKhachHang == null)
        {
            //JOptionPane.showMessageDialog(this,"kh null");
            quanLyKhachHang = new QuanLyKhachHang();
            tbpMain.addTab("Quản lý khách hàng",null,quanLyKhachHang,"Quản lý khách hàng");
            tbpMain.setSelectedComponent(quanLyKhachHang);
        }
        else if(tbpMain.getSelectedComponent().equals(quanLyKhachHang) == false)
        {
            //JOptionPane.showMessageDialog(this,"kh");
            tbpMain.setSelectedComponent(quanLyKhachHang);
            
        }
            
    }//GEN-LAST:event_menuItemKHActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void tbrAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAboutUsActionPerformed
        AboutUsDialog aboutUsDialog = new AboutUsDialog(this,true);
        aboutUsDialog.setVisible(true);
    }//GEN-LAST:event_tbrAboutUsActionPerformed

    private void menuItemAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutUsActionPerformed
        tbrAboutUsActionPerformed(evt);
    }//GEN-LAST:event_menuItemAboutUsActionPerformed

    Boolean isLogout = false;
    private void tbrLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogoutActionPerformed
        LoginDialog loginDialog = new LoginDialog(this, true);
        
        loginDialog.setVisible(true);
        isLogout = true;
        tbpMain.removeAll();;
        isLogout = false;
        quanLyBienLai=null;
        quanLyKhachHang=null;
        quanLyTaiKhoan=null;
        //JOptionPane.showMessageDialog(this,tbpMain.getTabCount());
        processLogin();
    }//GEN-LAST:event_tbrLogoutActionPerformed

    private void menuItemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTKActionPerformed
        if(quanLyTaiKhoan == null)
        {
            quanLyTaiKhoan = new QuanLyTaiKhoan();
            tbpMain.addTab("Quản lý tài khoản",null,quanLyTaiKhoan,"Quản lý tài khoản");
            tbpMain.setSelectedComponent(quanLyTaiKhoan);
            //JOptionPane.showMessageDialog(this,"tk null");
        }
        else 
        {
            tbpMain.setSelectedComponent(quanLyTaiKhoan);
            //JOptionPane.showMessageDialog(this,"tk");
        }
            
    }//GEN-LAST:event_menuItemTKActionPerformed

    private void menuItemBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBLActionPerformed
        if(quanLyBienLai == null)
        {
            quanLyBienLai = new QuanLyBienLai();
            tbpMain.addTab("Quản lý biên lai",null,quanLyBienLai,"Quản lý biên lai");
            //JOptionPane.showMessageDialog(this,"bl null");
            tbpMain.setSelectedComponent(quanLyBienLai);
        }
        else if(tbpMain.getSelectedComponent().equals(quanLyBienLai) == false)
        {
            tbpMain.setSelectedComponent(quanLyBienLai);
            //JOptionPane.showMessageDialog(this,"bl");
        }
    }//GEN-LAST:event_menuItemBLActionPerformed

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        tbrLogoutActionPerformed(evt);
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void tbrQLBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrQLBLActionPerformed
        menuItemBLActionPerformed(evt);
    }//GEN-LAST:event_tbrQLBLActionPerformed

    private void tbrQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrQLKHActionPerformed
        menuItemKHActionPerformed(evt);
    }//GEN-LAST:event_tbrQLKHActionPerformed

    private void tbrQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrQLTKActionPerformed
        menuItemTKActionPerformed(evt);
    }//GEN-LAST:event_tbrQLTKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginDialog loginDialog = new LoginDialog(this,true);
        loginDialog.setVisible(true);
        processLogin();
    }//GEN-LAST:event_formWindowOpened

    private void processLogin()
    {
        
        lblTenHienThi.setText(SharedData.nguoiDangNhapDung.getTenHienThi());
        lblVaiTro.setText(SharedData.nguoiDangNhapDung.getQuyenTaiKhoan());
        lblStatus.setText("Trạng thái: Sẵn sàng");
        jLabel2.setText("Thời gian: "+DataValidator.setCurentDateWithHour());
        
        
        if(SharedData.nguoiDangNhapDung.getQuyenTaiKhoan().equals("Quản trị"))
        {
            menuItemKH.setEnabled(true);
            menuItemBL.setEnabled(true);
            menuItemTK.setEnabled(true);
            tbrQLBL.setEnabled(true);
            tbrQLKH.setEnabled(true);
            tbrQLTK.setEnabled(true);
        }
        else if(SharedData.nguoiDangNhapDung.getQuyenTaiKhoan().equals("Người sử dụng"))
        {
            
            menuItemKH.setEnabled(true);
            menuItemBL.setEnabled(true);
            menuItemTK.setEnabled(false);
            tbrQLBL.setEnabled(true);
            tbrQLKH.setEnabled(true);
            tbrQLTK.setEnabled(false);
        }
    }
    
    private void tbpMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbpMainStateChanged
        //JOptionPane.showMessageDialog(this,tbpMain.getComponents().toString());
        if(isLogout == false)
        {
            quanLyBienLai.loadDataToCBB();
            quanLyBienLai.loadDataToTable();
//            if(tbpMain.getSelectedComponent().getClass().equals(quanLyBienLai.getClass()))
//            {
//               
//               JOptionPane.showMessageDialog(this,"vao bl");
//
//            }
//            else if(tbpMain.getSelectedComponent().getClass().equals(quanLyKhachHang.getClass()))
//            {
//                quanLyKhachHang = new QuanLyKhachHang();
//                JOptionPane.showMessageDialog(this,"vao kh");
//            }
//            else if(tbpMain.getSelectedComponent().getClass().equals(quanLyTaiKhoan.getClass()))
//            {
//                quanLyTaiKhoan = new QuanLyTaiKhoan();
//                JOptionPane.showMessageDialog(this,"vao tk");
//            }
        }
        

        
    }//GEN-LAST:event_tbpMainStateChanged

    private void tbpMainPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbpMainPropertyChange
        
        
    }//GEN-LAST:event_tbpMainPropertyChange

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        menuItemBLActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        menuItemKHActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        menuItemTKActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        tbrAboutUsActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        tbrLogoutActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuItemNdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNdActionPerformed
        HelpInfo helpInfo = new HelpInfo(this,true);
        helpInfo.setVisible(true);
    }//GEN-LAST:event_menuItemNdActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        menuItemNdActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTenHienThi;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JMenuItem menuItemAboutUs;
    private javax.swing.JMenuItem menuItemBL;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemKH;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemNd;
    private javax.swing.JMenuItem menuItemTK;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JTabbedPane tbpMain;
    private javax.swing.JButton tbrAboutUs;
    private javax.swing.JButton tbrLogout;
    private javax.swing.JButton tbrQLBL;
    private javax.swing.JButton tbrQLKH;
    private javax.swing.JButton tbrQLTK;
    // End of variables declaration//GEN-END:variables
}
