/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom23.quanlytiennuoc.ui;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.validation.Validator;
import nhom23.quanlytiennuoc.dao.BienLaiDao;
import nhom23.quanlytiennuoc.dao.KhachHangDao;
import nhom23.quanlytiennuoc.dao.NguoiDungDao;
import nhom23.quanlytiennuoc.helpers.DataValidator;
import nhom23.quanlytiennuoc.helpers.MessageDialogHelper;
import nhom23.quanlytiennuoc.model.BienLai;
import nhom23.quanlytiennuoc.model.KhachHang;
import nhom23.quanlytiennuoc.model.NguoiDung;

/**
 *
 * @author Admin
 */
public class QuanLyBienLai extends javax.swing.JPanel {
    private MainForm parentForm;
    private DefaultTableModel tblModel;
    private DefaultComboBoxModel<KhachHang> cbbBoxModelKH ;
    private DefaultComboBoxModel<NguoiDung> cbbBoxModelND ;
    /**
     * Creates new form QuanLyBienLai
     */
    public QuanLyBienLai() {
        
        initComponents();
        initTable();
        loadDataToTable();
        loadDataToCBB();
        txtMaBL.setText(UUID.randomUUID().toString());
        
    }

    public void loadDataToCBB()
    {
        KhachHangDao daoKH = new KhachHangDao();
        List<KhachHang> listKH = daoKH.getTable();
        cbbBoxModelKH = new DefaultComboBoxModel<KhachHang>();
        cbbMaCT.setModel(cbbBoxModelKH);
        for (KhachHang khachHang : listKH) {
            cbbBoxModelKH.addElement(khachHang);
        }
        
        NguoiDungDao daoND = new NguoiDungDao();
        List<NguoiDung> listND = daoND.getTable();
        cbbBoxModelND = new DefaultComboBoxModel<NguoiDung>();
        cbbMaTK.setModel(cbbBoxModelND);
        for (NguoiDung nguoiDung : listND) {
            cbbBoxModelND.addElement(nguoiDung);
        }
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã biên lại","Người lập biên lai","Ngày lập","Khách hàng","Chỉ số mới","Chỉ số cũ","Tổng tiền"});
        tblBienLai.setModel(tblModel);
        txtNgayLap.setText(DataValidator.setCurentDate());
    }
    
    public void loadDataToTable()
    {
        try {
            BienLaiDao dao = new BienLaiDao();
            NguoiDungDao nguoiDungDao = new NguoiDungDao();
            KhachHangDao khachHangDao = new KhachHangDao();
            List<BienLai> list = dao.getTable();
            tblModel.setRowCount(0);
            for (BienLai item : list) {
                var tenND = nguoiDungDao.findByID(item.getMaTK());
                var tenKH = khachHangDao.findByID(item.getMaCT()).getHoTen();
                tblModel.addRow(new Object[]{
                    item.getMaBL(), tenND,DataValidator.formatDateForTable(item.getNgayLap()),tenKH, item.getChiSoMoi(), item.getChiSoCu(), item.getTongTien(), 
                });
            txtNgayLap.setText(DataValidator.setCurentDate());    
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi load data");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtNgayLap = new javax.swing.JTextField();
        txtMaBL = new javax.swing.JTextField();
        txtChiSoMoi = new javax.swing.JTextField();
        txtChiSoCu = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnTinh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBienLai = new javax.swing.JTable();
        cbbMaTK = new javax.swing.JComboBox();
        cbbMaCT = new javax.swing.JComboBox();
        btnNew = new javax.swing.JButton();

        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Quản lý biên lai");

        jLabel2.setText("Mã công tơ:");

        jLabel3.setText("Tên Khách hàng:");

        jLabel4.setText("Người lập biên lai:");

        jLabel5.setText("Ngày lập:");

        jLabel6.setText("Mã biên lai:");

        jLabel7.setText("Địa chỉ:");

        jLabel8.setText("Số điện thoại:");

        jLabel9.setText("Chỉ số nước mới:");

        jLabel10.setText("Chỉ số nước cũ:");

        jLabel11.setText("Thành tiền:");

        txtTenKH.setEditable(false);

        txtDiaChi.setEditable(false);

        txtSoDienThoai.setEditable(false);

        txtNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLapActionPerformed(evt);
            }
        });

        txtThanhTien.setEditable(false);
        txtThanhTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtThanhTien.setForeground(new java.awt.Color(255, 0, 0));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Save-icon.png"))); // NOI18N
        btnSave.setText("Thêm");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnTinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/icons8_calculator_42px.png"))); // NOI18N
        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblBienLai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBienLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBienLaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBienLai);

        cbbMaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaCTActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/new-icon-16.png"))); // NOI18N
        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDiaChi)
                                    .addComponent(txtTenKH)
                                    .addComponent(txtSoDienThoai)
                                    .addComponent(cbbMaCT, 0, 178, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayLap)
                            .addComponent(txtMaBL)
                            .addComponent(cbbMaTK, 0, 205, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addComponent(txtChiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtChiSoCu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cbbMaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMaCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtChiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChiSoCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayLapActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        
       txtMaBL.setText(UUID.randomUUID().toString());
       txtTenKH.setText("");
       txtSoDienThoai.setText("");
       txtDiaChi.setText("");
       txtChiSoMoi.setText("");
       txtChiSoCu.setText("");
       txtThanhTien.setText("");
       txtNgayLap.setText("");
       
       loadDataToTable();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(txtThanhTien.getText() != null || txtThanhTien.getText() != "")
            txtThanhTien.setText("");
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaBL, sb, "Mã biên lai không được để trống");
        DataValidator.validateEmpty(txtChiSoMoi, sb, "Chỉ số nước mới không được để trống");
        DataValidator.validateNumber(txtChiSoMoi, sb);
        DataValidator.validateEmpty(txtChiSoCu, sb, "Chỉ số nước cũ không được để trống");
        DataValidator.validateNumber(txtChiSoCu, sb);
        DataValidator.validateEmpty(txtNgayLap, sb, "Ngày lập không được để trống");
        DataValidator.validateDateTime(txtNgayLap, sb, "Ngày phải nhập theo định dạo dd/MM/yyyy");
        DataValidator.validateEmpty(cbbMaCT, sb, "Phải chọn mã công tơ");
        DataValidator.validateEmpty(cbbMaTK, sb, "Phải chọn người lập biên lai");
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        BienLaiDao dao = null;
        try {
            BienLai bl = new BienLai();
            bl.setMaBL(txtMaBL.getText());
            bl.setChiSoMoi(Integer.parseInt(txtChiSoMoi.getText()));
            var csm = Integer.parseInt(txtChiSoMoi.getText());
            bl.setChiSoCu(Integer.parseInt(txtChiSoCu.getText()));
            var csc = Integer.parseInt(txtChiSoCu.getText());
            if(((csm-csc)*668) < 0)
            {
                MessageDialogHelper.showMessageDialog(parentForm, "Chỉ số mới không được nhỏ hợn chỉ số cũ", TOOL_TIP_TEXT_KEY);
                return;
            }
            bl.setTongTien(((csm-csc)*668));
            
            bl.setNgayLap(DataValidator.formatDate(txtNgayLap.getText()));
            
            bl.setMaCT(((KhachHang)cbbMaCT.getSelectedItem()).getMaCT());
            bl.setMaTK(((NguoiDung)cbbMaTK.getSelectedItem()).getMaTK());
            dao = new BienLaiDao();
            
            if(dao.Insert(bl))
            {
                MessageDialogHelper.showMessageDialog(parentForm, "Biên lai đã được lưu", "Thông báo");
                loadDataToTable();
                for (int i = 0; i < tblBienLai.getModel().getRowCount(); i++) {
                    if(tblBienLai.getModel().getValueAt(i, 0).equals(txtMaBL.getText()))
                    {
                        tblBienLai.setRowSelectionInterval(i, i);
                        break;
                    }
                    
                }
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentForm, "Biên lai chưa được lưu", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            if(dao.findByID(txtMaBL.getText()) != null)
            {
                MessageDialogHelper.showErrorDialog(parentForm, "Đã có mã biên lai trong cơ sở dự liệu", "Lỗi");
            }
            else
                MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(txtThanhTien.getText() != null || txtThanhTien.getText() != "")
            txtThanhTien.setText("");
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaBL, sb, "Mã biên lai không được để trống");
        DataValidator.validateEmpty(txtChiSoMoi, sb, "Chỉ số nước mới không được để trống");
        DataValidator.validateNumber(txtChiSoMoi, sb);
        DataValidator.validateEmpty(txtChiSoCu, sb, "Chỉ số nước cũ không được để trống");
        DataValidator.validateNumber(txtChiSoCu, sb);
        DataValidator.validateEmpty(txtNgayLap, sb, "Ngày lập không được để trống");
        DataValidator.validateDateTime(txtNgayLap, sb, "Ngày phải nhập theo định dạo dd/MM/yyyy");
        DataValidator.validateEmpty(cbbMaCT, sb, "Phải chọn mã công tơ");
        DataValidator.validateEmpty(cbbMaTK, sb, "Phải chọn người lập biên lai");
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn cập nhật biên lai không?", "Hỏi") == JOptionPane.NO_OPTION)
        {
            return;
        }
        BienLaiDao dao = null;
        try {
            BienLai bl = new BienLai();
            bl.setMaBL(txtMaBL.getText());
            bl.setChiSoMoi(Integer.parseInt(txtChiSoMoi.getText()));
            var csm = Integer.parseInt(txtChiSoMoi.getText());
            bl.setChiSoCu(Integer.parseInt(txtChiSoCu.getText()));
            var csc = Integer.parseInt(txtChiSoCu.getText());
            if(((csm-csc)*668) < 0)
            {
                MessageDialogHelper.showMessageDialog(parentForm, "Chỉ số mới không được nhỏ hợn chỉ số cũ", TOOL_TIP_TEXT_KEY);
                return;
            }
            bl.setTongTien(((csm-csc)*668));
            
            bl.setNgayLap(DataValidator.formatDate(txtNgayLap.getText()));
            
            bl.setMaCT(((KhachHang)cbbMaCT.getSelectedItem()).getMaCT());
            bl.setMaTK(((NguoiDung)cbbMaTK.getSelectedItem()).getMaTK());
            dao = new BienLaiDao();
            
            if(dao.Update(bl))
            {
                txtThanhTien.setText(String.valueOf(bl.getTongTien()));
                MessageDialogHelper.showMessageDialog(parentForm, "Biên lai đã được cập nhật", "Thông báo");
                loadDataToTable();
                for (int i = 0; i < tblBienLai.getModel().getRowCount(); i++) {
                    if(tblBienLai.getModel().getValueAt(i, 0).equals(txtMaBL.getText()))
                    {
                        tblBienLai.setRowSelectionInterval(i, i);
                        break;
                    }
                    
                }
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentForm, "Biên lai chưa được cập nhật", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            if(dao.findByID(txtMaBL.getText()) != null)
            {
                MessageDialogHelper.showErrorDialog(parentForm, "Đã có mã biên lai trong cơ sở dự liệu", "Lỗi");
            }
            else
                MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaBL, sb, "Mã biên lai không được để trống");
        
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa biên lai không?", "Hỏi") == JOptionPane.NO_OPTION)
        {
            return;
        }
        try {
            BienLaiDao dao = new BienLaiDao();
            
            if(dao.Delete(txtMaBL.getText()))
            {
                btnNewActionPerformed(null);
                MessageDialogHelper.showMessageDialog(parentForm, "Biên lai đã được xóa", "Thông báo");
                
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentForm, "Biên lai chưa được xóat", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cbbMaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaCTActionPerformed
        txtTenKH.setText(((KhachHang)cbbMaCT.getSelectedItem()).getHoTen());
        txtDiaChi.setText(((KhachHang)cbbMaCT.getSelectedItem()).getSoNha());
        txtSoDienThoai.setText(((KhachHang)cbbMaCT.getSelectedItem()).getSoDienThoai());
    }//GEN-LAST:event_cbbMaCTActionPerformed

    private void tblBienLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBienLaiMouseClicked
        try {
            int row = tblBienLai.getSelectedRow();
            
            if(row >= 0)
            {
                String id = (String) tblBienLai.getValueAt(row, 0);
                BienLaiDao dao = new BienLaiDao();
                KhachHangDao khachHangDao = new KhachHangDao();
                NguoiDungDao nguoiDungDao = new NguoiDungDao();
                BienLai bl = dao.findByID(id);
                
                if(bl != null)
                {
                    txtMaBL.setText(bl.getMaBL());
                    txtChiSoMoi.setText(String.valueOf(bl.getChiSoMoi()));
                    txtChiSoCu.setText(String.valueOf(bl.getChiSoCu()));
                    txtThanhTien.setText(String.valueOf(bl.getTongTien()));
                    
                    txtNgayLap.setText(DataValidator.formatDateForTable(bl.getNgayLap()));
                    
                    cbbBoxModelKH.setSelectedItem(khachHangDao.findByID(bl.getMaCT()));
                    cbbBoxModelND.setSelectedItem(nguoiDungDao.findByID(bl.getMaTK()));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblBienLaiMouseClicked

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        if(txtThanhTien.getText() != null || txtThanhTien.getText() != "")
            txtThanhTien.setText("");
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtChiSoMoi, sb, "Chỉ số nước mới không được để trống");
        DataValidator.validateNumber(txtChiSoMoi, sb);
        DataValidator.validateEmpty(txtChiSoCu, sb, "Chỉ số nước cũ không được để trống");
        DataValidator.validateNumber(txtChiSoCu, sb);
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        var csm = Integer.parseInt(txtChiSoMoi.getText());
        var csc = Integer.parseInt(txtChiSoCu.getText());
        var kq = (csm - csc)*668;
        if(kq > 0)
        {
            txtThanhTien.setText(String.valueOf(kq));
        }
        else
        {
            MessageDialogHelper.showMessageDialog(parentForm, "Chỉ số mới không được nhỏ hợn chỉ số cũ", "Thông báo");
        }
        
        
    }//GEN-LAST:event_btnTinhActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        
    }//GEN-LAST:event_formPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTinh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbbMaCT;
    private javax.swing.JComboBox cbbMaTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblBienLai;
    private javax.swing.JTextField txtChiSoCu;
    private javax.swing.JTextField txtChiSoMoi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaBL;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
