/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom23.quanlytiennuoc.ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nhom23.quanlytiennuoc.dao.KhachHangDao;
import nhom23.quanlytiennuoc.dao.NguoiDungDao;
import nhom23.quanlytiennuoc.helpers.DataValidator;
import nhom23.quanlytiennuoc.helpers.MessageDialogHelper;
import nhom23.quanlytiennuoc.model.KhachHang;

/**
 *
 * @author Admin
 */

public class QuanLyKhachHang extends javax.swing.JPanel {
    private MainForm parentForm;
    private DefaultTableModel tblModel;
    
    public QuanLyKhachHang() {
        initComponents();
        initTable();
        loadDataToTable();
    }

    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã công tơ","Họ tên","Địa chỉ","Số điện thoại"});
        tblKhachHang.setModel(tblModel);
    }
    
    private void loadDataToTable()
    {
        try {
            KhachHangDao dao = new KhachHangDao();
            List<KhachHang> list = dao.getTable();
            tblModel.setRowCount(0);
            for (KhachHang item : list) {
                tblModel.addRow(new Object[]{
                    item.getMaCT(), item.getHoTen(), item.getSoNha(), item.getSoDienThoai()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMaCT = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("Mã công tơ:");

        jLabel2.setText("Họ tên khách hàng:");

        jLabel3.setText("Địa chỉ nhà:");

        jLabel4.setText("Số điện thoại:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Quản lý khách hàng");

        txtMaCT.setText("CT01");

        txtHoten.setText("Vũ Văn Quyết");

        txtDiaChi.setText("666 Hải Dương");
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        txtSoDienThoai.setText("222222222222");

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/new-icon-16.png"))); // NOI18N
        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom23/quanlytiennuoc/icons/Save-icon.png"))); // NOI18N
        btnSave.setText("Thêm");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaCT)
                            .addComponent(txtHoten)
                            .addComponent(txtDiaChi)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnSave, btnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDelete, btnSave, btnUpdate});

    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       txtMaCT.setText("");
       txtMaCT.setEditable(true);
       txtHoten.setText("");
       txtDiaChi.setText("");
       txtSoDienThoai.setText("");
       loadDataToTable();
       
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaCT, sb, "Mã công tơ không được để trống");
        DataValidator.validateEmpty(txtHoten, sb, "Tên không được để trống");
        DataValidator.validateEmpty(txtDiaChi, sb, "Địa chỉ không được để trống");
        DataValidator.validateEmpty(txtSoDienThoai, sb, "Số điện thoại không được để trống");
        DataValidator.validatePhoneNumber(txtSoDienThoai, sb);
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        KhachHangDao dao = null;
        try {
            KhachHang kh = new KhachHang();
            kh.setMaCT(txtMaCT.getText());
            kh.setHoTen(txtHoten.getText());
            kh.setSoNha(txtDiaChi.getText());
            kh.setSoDienThoai(txtSoDienThoai.getText());
            dao = new KhachHangDao();
            if(dao.Insert(kh))
            {
                MessageDialogHelper.showMessageDialog(parentForm, "Khách hàng đã được lưu", "Thông báo");
                loadDataToTable();
                for (int i = 0; i < tblKhachHang.getModel().getRowCount(); i++) {
                    if(tblKhachHang.getModel().getValueAt(i, 0).equals(txtMaCT.getText()))
                    {
                        tblKhachHang.setRowSelectionInterval(i, i);
                        break;
                    }
                    
                }
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentForm, "Khách hàng chưa được lưu", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            if(dao.findByID(txtMaCT.getText()) != null)
            {
                MessageDialogHelper.showErrorDialog(parentForm, "Đã có mã công tơ trong cơ sở dự liệu", "Lỗi");
            }
            else
                MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaCT, sb, "Mã công tơ không được để trống");
        DataValidator.validateEmpty(txtHoten, sb, "Tên không được để trống");
        DataValidator.validateEmpty(txtDiaChi, sb, "Địa chỉ không được để trống");
        DataValidator.validateEmpty(txtSoDienThoai, sb, "Số điện thoại không được để trống");
        DataValidator.validatePhoneNumber(txtSoDienThoai, sb);
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn cập nhật khách hàng không?", "Hỏi") == JOptionPane.NO_OPTION)
        {
            return;
        }
        KhachHangDao dao = null;
        try {
            KhachHang kh = new KhachHang();
            kh.setMaCT(txtMaCT.getText());
            kh.setHoTen(txtHoten.getText());
            kh.setSoNha(txtDiaChi.getText());
            kh.setSoDienThoai(txtSoDienThoai.getText());
            dao = new KhachHangDao();
            if(dao.Update(kh))
            {
                MessageDialogHelper.showMessageDialog(parentForm, "Khách hàng đã được cập nhật", "Thông báo");
                loadDataToTable();
                for (int i = 0; i < tblKhachHang.getModel().getRowCount(); i++) {
                    if(tblKhachHang.getModel().getValueAt(i, 0).equals(txtMaCT.getText()))
                    {
                        tblKhachHang.setRowSelectionInterval(i, i);
                        break;
                    }
                    
                }
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentForm, "Khách hàng chưa được cập nhật", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            if(dao.findByID(txtMaCT.getText()) != null)
            {
                MessageDialogHelper.showErrorDialog(parentForm, "Đã có mã công tơ trong cơ sở dự liệu", "Lỗi");
            }
            else
                MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtMaCT, sb, "Mã công tơ không được để trống");
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa khách hàng không?", "Hỏi") == JOptionPane.NO_OPTION)
        {
            return;
        }
        try {
            
            KhachHangDao dao = new KhachHangDao();
            if(dao.Delete(txtMaCT.getText()))
            {
                MessageDialogHelper.showMessageDialog(parentForm, "Khách hàng đã được xóa", "Thông báo");
                btnNewActionPerformed(evt);
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentForm, "Khách hàng chưa được xóa", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        try {
            int row = tblKhachHang.getSelectedRow();
            
            if(row >= 0)
            {
                String id = (String) tblKhachHang.getValueAt(row, 0);
                KhachHangDao dao = new KhachHangDao();
                KhachHang kh = dao.findByID(id);
                
                if(kh != null)
                {
                    txtMaCT.setText(kh.getMaCT());
                    txtMaCT.setEditable(false);;
                    txtHoten.setText(kh.getHoTen());
                    txtDiaChi.setText(kh.getSoNha());
                    txtSoDienThoai.setText(kh.getSoDienThoai());
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaCT;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
